### ISSUE TITLE
Properly configure NPM publication for v5 and v6 versions

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/react-data-view#11]

**Comment by nicolethoen** [comment]
it's done! the v5 branches and main branches are poised!

v5 brach will release only minor/patch branches in a 5.x release stream.
main branch will release 6.0.0-prerelease.x versions until ready for an official 6.0.0 release

FYI @fhlavac

**Comment by fhlavac** [comment]
@nicolethoen awesome work! Thank you so much!
